---
title: "Gov 50 Final Project"
author: "Nuriel Vera-DeGraff"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Milestone 1: Repository 
## I am interested in exploring data related to elections and polling, particularly data regarding polling/election prediction accuracy and data that could allow me to compare different weighting strategies in the polling process.

## Milestone 2: Data and Proposal
## How do the demographics of a state's voting population affect the demographics of its legislature? In my study, I will attempt to quantify the relationship/correlation between state populations' racial and gender diversity rates and their respective legislatures' racial and gender diversity rates. I hypothesize that racial and gender diversity in state populations will be positively correlated with the same kind of diversity in their state legislatures. This hypothesis follows from the theory that people are more likely to vote for candidates who are more similar to them, and so states with voting populations that have higher concentrations of different racial/ethnic groups will see a related increase in the concentrations of legislators from those racial/ethnic groups. My explanatory variables of interest are the total Asian population in the given state legislature district, as well as the total Hispanic/Latino population, the total Black population, the total white population, the total Native Hawaiian population, and the total Native American population. Each of these variables are measured by a raw count, which reflects the number of people in each of these groups. My outcome variables are the assigned race/ethnicity and gender of the state legislator of the given district, which are measured qualitatively (White, Black, etc. for race/ethnicity and male/female/etc. for gender). If I observe a positive correlation either between the general diversity of states' populations and the diversity of their state legislators OR between the concentration of certain racial groups in states' populations and and concentrations of those same racial groups in respective states' legislative bodies, my hypothesis would be supported. However, a lack of correlation (and perhaps even a negative correlation) between either of these two variables would work against my hypothesis. My data will likely be from https://www.legislatordiversity.com/.
